### PR TITLE
Fixed TitleKey and BodyKey implementation.

### PR DESCRIPTION
**Pull request by socraticbliss**
You could do this or take out the *2...

As XTS is 0x200

### CODE REVIEW

**Comment by jakcron** [comment]
--titlekey and --bodykey are supposed to support 16byte aes keys (for aes-ctr and aes-ctr-ex) and 32byte keys for (aes-xts). 

But since a byte in string form is represented in two chars. This means it has to be able to accept 32 and 64 lengths strings.

**Comment by jakcron** [comment]
I’ll clean up the logic so it’s easier to read.

**Comment by jakcron** [comment]
But your fix will break it.

**Comment by socraticbliss** [comment]
Ah, well the Title Keys that I have collected have always been lengths of 0x10... hactool is also expecting that length...

            case 12:
                parse_hex_key(nca_ctx.tool_ctx->settings.titlekey, optarg, 16);

https://github.com/SciresM/hactool/blob/master/main.c

**Comment by jakcron** [comment]
AES-XTS is a valid NCA body encryption mode. 

Also hactool expects lengths of 32 bytes for key lengths of 16. Just check parse_hex_key()...
if (strlen(hex) != 2 * len) {
        fprintf(stderr, "Key (%s) must be %"PRIu32" hex digits!\n", hex, 2 * len);
        exit(EXIT_FAILURE);
    }

**Comment by socraticbliss** [comment]
I'm not sure honestly, as before I was getting an invalid key length, but I just compiled the latest and now it's accepting it maybe? Very strange... When trying to decrypt my octopath demo, I get a PFS header error, it's probably my bad for not including a body key perhaps? I'll double check when I'm home again tonight, thanks for the responses though :)

**Comment by jakcron** [comment]
@socraticbliss it's more than possible there are issues with handling crypto with NCA files that require a titlekey. I don't have any myself, so I can't test it. Is there a way I can contact you outside github?

**Comment by jakcron** [comment]
https://github.com/jakcron/NXTools/commit/c7e79b1d55ace16e7fbed27c7a3514bd89a6efe4

**Pull request closed without merging**
